In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import ShuffleSplit
from sklearn.preprocessing import StandardScaler, LabelEncoder

/Users/aaron/Documents/ml/kaggle/venv/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
test_df = pd.read_csv('test.csv')
test_df.to_csv('test-orig.csv')
test_df.tail()

FileNotFoundError: File b'test.csv' does not exist

In [16]:
df = pd.read_csv('train.csv')
df.shape

(891, 12)

In [17]:
df['Age'] = df['Age'].fillna(0)

In [18]:
df['Age'][50:65]

50     7.0
51    21.0
52    49.0
53    29.0
54    65.0
55     0.0
56    21.0
57    28.5
58     5.0
59    11.0
60    22.0
61    38.0
62    45.0
63     4.0
64     0.0
Name: Age, dtype: float64

In [13]:
df.to_csv('test.csv', index=False)
df.tail()

{type(t) for t in df['Age'].values}

{numpy.float64}

In [10]:
examples = df.shape[0]
train = int(examples * .8)
validation = examples - train

print('train:', train)
print('validation:', validation)

train: 712
validation: 179


In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
for column in df.columns:
    #if column not in ('PassengerId' 'Name'):
    print(column, df[column].unique())

PassengerId [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 24

In [83]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [85]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [92]:
# male = 1; female = 0
le_sex = LabelEncoder().fit_transform(df['Sex'])
print(le_sex[:4])
print(df['Sex'][:4])

[1 0 0 0]
0      male
1    female
2    female
3    female
Name: Sex, dtype: object


In [97]:
le_age = StandardScaler().fit_transform(df['Age'].fillna(0)[:, None])
print(le_age.size)

891


In [99]:
le_fare = StandardScaler().fit_transform(df['Fare'][:, None])

In [110]:
types = set()
for x in df['Cabin'].fillna('').unique():
    types.add(type(x))
types

le_cabin = LabelEncoder().fit_transform(df['Cabin'].fillna(''))

In [113]:
le_embarked = LabelEncoder().fit_transform(df['Embarked'].fillna(''))

In [122]:
# le_sex
# le_age
# le_fare
# le_cabin
# le_embarked
# df['Pclass']
# df['SibSp']
# df['Parch']

le_age = np.squeeze(le_age)
le_fare = np.squeeze(le_fare)

for idx, x in enumerate([le_sex, le_age, le_fare, le_cabin, le_embarked ,df['Pclass'], df['SibSp'], df['Parch']]):
    print(idx, x.shape, type(x))

0 (891,) <class 'numpy.ndarray'>
1 (891,) <class 'numpy.ndarray'>
2 (891,) <class 'numpy.ndarray'>
3 (891,) <class 'numpy.ndarray'>
4 (891,) <class 'numpy.ndarray'>
5 (891,) <class 'pandas.core.series.Series'>
6 (891,) <class 'pandas.core.series.Series'>
7 (891,) <class 'pandas.core.series.Series'>


In [121]:
print(le_age.shape)
np.squeeze(le_age).shape

(891, 1)


(891,)

In [15]:
columns_to_ignore = ('PassengerId', 'Name', 'Ticket')

for column in df.columns:
    if column not in columns_to_ignore:
        print(column, df[column].unique())

Survived [0 1]
Pclass [3 1 2]
Sex ['male' 'female']
Age [ 22.    38.    26.    35.      nan  54.     2.    27.    14.     4.    58.
  20.    39.    55.    31.    34.    15.    28.     8.    19.    40.    66.
  42.    21.    18.     3.     7.    49.    29.    65.    28.5    5.    11.
  45.    17.    32.    16.    25.     0.83  30.    33.    23.    24.    46.
  59.    71.    37.    47.    14.5   70.5   32.5   12.     9.    36.5   51.
  55.5   40.5   44.     1.    61.    56.    50.    36.    45.5   20.5   62.
  41.    52.    63.    23.5    0.92  43.    60.    10.    64.    13.    48.
   0.75  53.    57.    80.    70.    24.5    6.     0.67  30.5    0.42
  34.5   74.  ]
SibSp [1 0 3 4 2 5 8]
Parch [0 1 2 5 3 4 6]
Fare [   7.25     71.2833    7.925    53.1       8.05      8.4583   51.8625
   21.075    11.1333   30.0708   16.7      26.55     31.275     7.8542
   16.       29.125    13.       18.        7.225    26.        8.0292
   35.5      31.3875  263.        7.8792    7.8958   27.7208  1

In [37]:
VALID = df.shape[0] // 9 # 1/9th will be "dev set" data

In [130]:
# all_df = df.drop(['PassengerId', 'Name', 'Ticket'], axis=1)
# test_df = all_df[:-VALID]
# dev_df = all_df[:VALID]

all_df = np.array([le_sex, le_age, le_fare, le_cabin, le_embarked ,df['Pclass'], df['SibSp'], df['Parch']])

test_df = np.array([x[:-VALID] for x in all_df])
dev_df = np.array([x[:VALID] for x in all_df])


print(test_df.shape)
print(dev_df.shape)

(8, 792)
(8, 99)


In [152]:
# 2nd attempt

# Specify that all features have real-value data
feature_columns = [tf.feature_column.numeric_column("x", shape=[8])]

# Build 3 layer DNN with 10, 20, 10 units respectively.
classifier = tf.estimator.DNNClassifier(feature_columns=feature_columns,
                                        hidden_units=[10, 20, 10],
                                        n_classes=3,
                                        model_dir="/tmp/titanic")

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/titanic', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x116dc0be0>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [155]:
# Define the training inputs
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": np.array(test_df.T)},
    y=np.array(df['Survived'][:-VALID]),
    num_epochs=None,
    shuffle=True)

In [156]:
# Train model.
classifier.train(input_fn=train_input_fn, steps=200)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from /tmp/titanic/model.ckpt-2003


InvalidArgumentError: tensor_name = dnn/hiddenlayer_0/kernel; shape in shape_and_slice spec [8,10] does not match the shape stored in checkpoint: [1,10]
	 [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]

Caused by op 'save/RestoreV2_2', defined at:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 281, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 232, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 397, in execute_request
    user_expressions, allow_stdin)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2856, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-156-de24f59589fa>", line 2, in <module>
    classifier.train(input_fn=train_input_fn, steps=200)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 780, in _train_model
    log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 368, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 673, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 493, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 851, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 856, in _create_session
    return self._sess_creator.create_session()
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 554, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 419, in create_session
    self._scaffold.finalize()
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 212, in finalize
    self._saver.build()
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 745, in _build_internal
    restore_sequentially, reshape)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 470, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/Users/aaron/Documents/ml/kaggle/digit-recognizer/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): tensor_name = dnn/hiddenlayer_0/kernel; shape in shape_and_slice spec [8,10] does not match the shape stored in checkpoint: [1,10]
	 [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]


In [81]:
# Define the test inputs
test_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": np.array(dev_df['Age'].values)},
    y=np.array(dev_df['Survived'].fillna(0).values),
    num_epochs=1,
    shuffle=False)

# Evaluate accuracy.
accuracy_score = classifier.evaluate(input_fn=test_input_fn)["accuracy"]

print("\nTest Accuracy: {0:f}\n".format(accuracy_score))

INFO:tensorflow:Starting evaluation at 2018-01-13-22:48:36
INFO:tensorflow:Restoring parameters from /tmp/titanic/model.ckpt-2003
INFO:tensorflow:Finished evaluation at 2018-01-13-22:48:37
INFO:tensorflow:Saving dict for global step 2003: accuracy = 0.585859, accuracy_baseline = 0.585859, auc = 0.485702, auc_precision_recall = 0.427263, average_loss = 0.69295, global_step = 2003, label/mean = 0.414141, loss = 68.6021, prediction/mean = 0.37602

Test Accuracy: 0.585859



In [216]:
# Specify that all features have real-value data
feature_columns = [tf.feature_column.numeric_column("x", shape=[8])]

# Build 3 layer DNN with 10, 20, 10 units respectively.
classifier = tf.estimator.DNNClassifier(feature_columns=feature_columns,
                                      hidden_units=[10, 20, 10],
                                      n_classes=2,
                                      model_dir="/tmp/titanic2")
# Define the training inputs
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": np.array(test_df.T)},
    y=np.array(df['Survived'][:-VALID]),
    num_epochs=None,
    shuffle=True)

# Train model.
classifier.train(input_fn=train_input_fn, steps=2000)

# Define the test inputs
test_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": np.array(dev_df.T)},
    y=np.array(df['Survived'][:VALID]),
    num_epochs=1,
    shuffle=False)

# Evaluate accuracy.
accuracy_score = classifier.evaluate(input_fn=test_input_fn)["accuracy"]

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/titanic2', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x11c7b9710>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from /tmp/titanic2/model.ckpt-4000
INFO:tensorflow:Saving checkpoints for 4001 into /tmp/titanic2/model.ckpt.
INFO:tensorflow:loss = 36.6297, step = 4001
INFO:tensorflow:global_step/sec: 527.582
INFO:tensorflow:loss = 50.2115, step = 4101 (0.191 sec)
INFO:tensorflow:global_step/sec: 584.003
INFO:tensorflow:loss = 54.9796, step = 4201 (0.171 sec

In [217]:
accuracy_score

0.87878788

In [212]:
pdf = pd.read_csv('test.csv')

ple_sex = LabelEncoder().fit_transform(pdf['Sex'])
ple_age = StandardScaler().fit_transform(pdf['Age'].fillna(0)[:, None])
ple_fare = StandardScaler().fit_transform(pdf['Fare'].fillna(0)[:, None])
ple_cabin = LabelEncoder().fit_transform(pdf['Cabin'].fillna(''))
ple_embarked = LabelEncoder().fit_transform(pdf['Embarked'].fillna(''))

ple_age = np.squeeze(ple_age)
ple_fare = np.squeeze(ple_fare)

pall_pdf = np.array([ple_sex, ple_age, ple_fare, ple_cabin, ple_embarked ,pdf['Pclass'], pdf['SibSp'], pdf['Parch']])

print(pall_pdf.T.shape)

predict_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": pall_pdf.T},
    num_epochs=1,
    shuffle=False)

predictions = classifier.predict(input_fn=predict_input_fn)
# predicted_classes = [p["classes"] for p in predictions]

(418, 8)


In [213]:
predicted_classes = [p["classes"][0].decode('utf8') for p in predictions]

INFO:tensorflow:Restoring parameters from /tmp/titanic2/model.ckpt-4000


In [214]:
# results = [int(x[0].decode('utf8') for x in predicted_classes)]

predicted_classes

['0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0',
 '1',
 '0',
 '1',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0',
 '1',
 '1',
 '0',
 '1',
 '0',
 '1',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '0',
 '1',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '1',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0',
 '1',
 '0',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '1',
 '0',
 '1',
 '0',
 '1',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '1',
 '1',
 '0',
 '1',
 '0',
 '0',
 '1',
 '0',
 '1',
 '1',
 '0',
 '1',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0'

In [215]:
submission = pd.DataFrame(data={'PassengerId': pdf['PassengerId'], 'Survived': predicted_classes})
submission.to_csv('submission.csv', index=False)
submission.tail()

PassengerId Survived
413         1305        0
414         1306        1
415         1307        0
416         1308        0
417         1309        1

In [205]:
len(predicted_classes)

418

In [20]:
submission.head()

NameError: name 'submission' is not defined

In [24]:
import csv

filename = "input/csv_test_data.csv"

with open(filename, 'w', newline='') as csvfile:
    spamwriter = csv.writer(csvfile)
    spamwriter.writerow(['A', 'B', 'C', 'D', 'E'])
    for i in range(5):
        spamwriter.writerow([0, 0, 0, 0, 0])

In [44]:
from __future__ import print_function
import tensorflow as tf

def file_len(fname):
    with open(fname) as f:
        for i, l in enumerate(f):
            pass
    return i + 1

# setup text reader
file_length = file_len(filename)
filename_queue = tf.train.string_input_producer([filename])
reader = tf.TextLineReader(skip_header_lines=1)
_, csv_row = reader.read(filename_queue)

# setup CSV decoding
record_defaults = [[0],[0],[0],[0],[0]]
col1,col2,col3,col4,col5 = tf.decode_csv(csv_row, record_defaults=record_defaults)

# turn features back into a tensor
features = tf.stack([col1,col2,col3,col4])

print("loading, " + str(file_length) + " line(s)\n")
with tf.Session() as sess:
  tf.initialize_all_variables().run()

  # start populating filename queue
  coord = tf.train.Coordinator()
  threads = tf.train.start_queue_runners(coord=coord)

  for i in range(file_length):
    # retrieve a single instance
    example, label = sess.run([features, col5])
    print(example, label)

  coord.request_stop()
  coord.join(threads)
  print("\ndone loading")

loading, 6 line(s)

[0 0 0 0] 0
[0 0 0 0] 0
[0 0 0 0] 0
[0 0 0 0] 0
[0 0 0 0] 0
[0 0 0 0] 0

done loading


In [38]:
e = example
e

array([0, 0, 0, 0], dtype=int32)

In [41]:
np.array([e, e])

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [43]:
np.put?

In [1]:
!pwd

/Users/aaron/Documents/ml/kaggle/titanic
